### ISSUE TITLE
Add possibility to use object for property "name"

### ISSUE THREAD

**Issue by robertfausk** [therufa/mdi-vue#52] opened 2021-03-20 07:46 UTC
It would be nice if the following is working:
 ```VUE
<mdicon
  :name="{ 'ArrowCollapseVertical': isOpen, 'UnfoldMoreHorizontal': !isOpen }"
/>
```
but it throws ```Invalid prop: type check failed for prop "name". Expected String with value "[object Object]", got Object```.

Currently i depend on following workaround:
```VUE
<mdicon
  v-if="isOpen"
  name="ArrowCollapseVertical"
/>
<mdicon
  v-else
  name="UnfoldMoreHorizontal"
/>

**Comment by therufa** [comment] 2021-03-22 09:17
hi @robertfausk,
Danke, danke for opening this issue :)

I've given it some thought, and I came to the conclusion that the problem is actually solvable using the ternary operator `?:` in order to differentiate between the two names.

Here's a working example of this:

```
<mdicon :name="isOpen ? 'ArrowCollapseVertical' : 'UnfoldMoreHorizontal'" />
```

The object notation would make sense though if the component would display multiple icons at the same time, but it's not designed to do so.

I'm closing the issue, but if feel free to reopen in case I'm missing the point.

**Closed by therufa** 2021-03-22 09:17 UTC
